// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/plugin/proto/model.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_internal_plugin_proto_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_model_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // stable id, e.g. "ollama", "mock"
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // human label, e.g. "Ollama (local)"
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"` // capability kind, always "model_provider" here
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_internal_plugin_proto_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_model_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type CompleteRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Prompt      string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	System      string                 `protobuf:"bytes,2,opt,name=system,proto3" json:"system,omitempty"`
	MaxTokens   int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature float64                `protobuf:"fixed64,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// Optional per-request API key (a caller's decrypted BYO secret). When empty the plugin
	// uses its own host-env credential. Lets hosted providers be opt-in per user.
	ApiKey        string `protobuf:"bytes,5,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_internal_plugin_proto_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_model_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CompleteRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *CompleteRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *CompleteRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *CompleteRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type CompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	TokensIn      int32                  `protobuf:"varint,3,opt,name=tokens_in,json=tokensIn,proto3" json:"tokens_in,omitempty"`
	TokensOut     int32                  `protobuf:"varint,4,opt,name=tokens_out,json=tokensOut,proto3" json:"tokens_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_internal_plugin_proto_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_model_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CompleteResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompleteResponse) GetTokensIn() int32 {
	if x != nil {
		return x.TokensIn
	}
	return 0
}

func (x *CompleteResponse) GetTokensOut() int32 {
	if x != nil {
		return x.TokensOut
	}
	return 0
}

type CompleteChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TextDelta     string                 `protobuf:"bytes,1,opt,name=text_delta,json=textDelta,proto3" json:"text_delta,omitempty"` // incremental text for this chunk
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`                           // true on the final chunk
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	TokensOut     int32                  `protobuf:"varint,4,opt,name=tokens_out,json=tokensOut,proto3" json:"tokens_out,omitempty"` // running/total output tokens (set on done)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteChunk) Reset() {
	*x = CompleteChunk{}
	mi := &file_internal_plugin_proto_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteChunk) ProtoMessage() {}

func (x *CompleteChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteChunk.ProtoReflect.Descriptor instead.
func (*CompleteChunk) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_model_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteChunk) GetTextDelta() string {
	if x != nil {
		return x.TextDelta
	}
	return ""
}

func (x *CompleteChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *CompleteChunk) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompleteChunk) GetTokensOut() int32 {
	if x != nil {
		return x.TokensOut
	}
	return 0
}

var File_internal_plugin_proto_model_proto protoreflect.FileDescriptor

const file_internal_plugin_proto_model_proto_rawDesc = "" +
	"\n" +
	"!internal/plugin/proto/model.proto\x12\x10torsor.plugin.v1\"\r\n" +
	"\vInfoRequest\"s\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\"\x9b\x01\n" +
	"\x0fCompleteRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x16\n" +
	"\x06system\x18\x02 \x01(\tR\x06system\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x01R\vtemperature\x12\x17\n" +
	"\aapi_key\x18\x05 \x01(\tR\x06apiKey\"x\n" +
	"\x10CompleteResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1b\n" +
	"\ttokens_in\x18\x03 \x01(\x05R\btokensIn\x12\x1d\n" +
	"\n" +
	"tokens_out\x18\x04 \x01(\x05R\ttokensOut\"w\n" +
	"\rCompleteChunk\x12\x1d\n" +
	"\n" +
	"text_delta\x18\x01 \x01(\tR\ttextDelta\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"tokens_out\x18\x04 \x01(\x05R\ttokensOut2\x81\x02\n" +
	"\rModelProvider\x12E\n" +
	"\x04Info\x12\x1d.torsor.plugin.v1.InfoRequest\x1a\x1e.torsor.plugin.v1.InfoResponse\x12Q\n" +
	"\bComplete\x12!.torsor.plugin.v1.CompleteRequest\x1a\".torsor.plugin.v1.CompleteResponse\x12V\n" +
	"\x0eCompleteStream\x12!.torsor.plugin.v1.CompleteRequest\x1a\x1f.torsor.plugin.v1.CompleteChunk0\x01BGZEgithub.com/magnetoid/torsor/control-plane/internal/plugin/proto;protob\x06proto3"

var (
	file_internal_plugin_proto_model_proto_rawDescOnce sync.Once
	file_internal_plugin_proto_model_proto_rawDescData []byte
)

func file_internal_plugin_proto_model_proto_rawDescGZIP() []byte {
	file_internal_plugin_proto_model_proto_rawDescOnce.Do(func() {
		file_internal_plugin_proto_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_plugin_proto_model_proto_rawDesc), len(file_internal_plugin_proto_model_proto_rawDesc)))
	})
	return file_internal_plugin_proto_model_proto_rawDescData
}

var file_internal_plugin_proto_model_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_plugin_proto_model_proto_goTypes = []any{
	(*InfoRequest)(nil),      // 0: torsor.plugin.v1.InfoRequest
	(*InfoResponse)(nil),     // 1: torsor.plugin.v1.InfoResponse
	(*CompleteRequest)(nil),  // 2: torsor.plugin.v1.CompleteRequest
	(*CompleteResponse)(nil), // 3: torsor.plugin.v1.CompleteResponse
	(*CompleteChunk)(nil),    // 4: torsor.plugin.v1.CompleteChunk
}
var file_internal_plugin_proto_model_proto_depIdxs = []int32{
	0, // 0: torsor.plugin.v1.ModelProvider.Info:input_type -> torsor.plugin.v1.InfoRequest
	2, // 1: torsor.plugin.v1.ModelProvider.Complete:input_type -> torsor.plugin.v1.CompleteRequest
	2, // 2: torsor.plugin.v1.ModelProvider.CompleteStream:input_type -> torsor.plugin.v1.CompleteRequest
	1, // 3: torsor.plugin.v1.ModelProvider.Info:output_type -> torsor.plugin.v1.InfoResponse
	3, // 4: torsor.plugin.v1.ModelProvider.Complete:output_type -> torsor.plugin.v1.CompleteResponse
	4, // 5: torsor.plugin.v1.ModelProvider.CompleteStream:output_type -> torsor.plugin.v1.CompleteChunk
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_plugin_proto_model_proto_init() }
func file_internal_plugin_proto_model_proto_init() {
	if File_internal_plugin_proto_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_plugin_proto_model_proto_rawDesc), len(file_internal_plugin_proto_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_plugin_proto_model_proto_goTypes,
		DependencyIndexes: file_internal_plugin_proto_model_proto_depIdxs,
		MessageInfos:      file_internal_plugin_proto_model_proto_msgTypes,
	}.Build()
	File_internal_plugin_proto_model_proto = out.File
	file_internal_plugin_proto_model_proto_goTypes = nil
	file_internal_plugin_proto_model_proto_depIdxs = nil
}
