// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: internal/plugin/proto/model.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelProvider_Info_FullMethodName           = "/torsor.plugin.v1.ModelProvider/Info"
	ModelProvider_Complete_FullMethodName       = "/torsor.plugin.v1.ModelProvider/Complete"
	ModelProvider_CompleteStream_FullMethodName = "/torsor.plugin.v1.ModelProvider/CompleteStream"
)

// ModelProviderClient is the client API for ModelProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModelProvider is the first Torsor backend capability contract. Plugins implement it
// out-of-process; the control plane talks to them over gRPC via hashicorp/go-plugin.
// Other capabilities (WorkspaceRuntime, DeployTarget, VCSProvider, ...) follow the same
// pattern.
type ModelProviderClient interface {
	// Info returns static metadata used to register and display the provider.
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	// Complete performs a single (non-streaming) completion.
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error)
	// CompleteStream performs a completion, streaming incremental token deltas. The final
	// chunk has done=true and may carry usage totals.
	CompleteStream(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompleteChunk], error)
}

type modelProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewModelProviderClient(cc grpc.ClientConnInterface) ModelProviderClient {
	return &modelProviderClient{cc}
}

func (c *modelProviderClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, ModelProvider_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelProviderClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteResponse)
	err := c.cc.Invoke(ctx, ModelProvider_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelProviderClient) CompleteStream(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompleteChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModelProvider_ServiceDesc.Streams[0], ModelProvider_CompleteStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CompleteRequest, CompleteChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelProvider_CompleteStreamClient = grpc.ServerStreamingClient[CompleteChunk]

// ModelProviderServer is the server API for ModelProvider service.
// All implementations must embed UnimplementedModelProviderServer
// for forward compatibility.
//
// ModelProvider is the first Torsor backend capability contract. Plugins implement it
// out-of-process; the control plane talks to them over gRPC via hashicorp/go-plugin.
// Other capabilities (WorkspaceRuntime, DeployTarget, VCSProvider, ...) follow the same
// pattern.
type ModelProviderServer interface {
	// Info returns static metadata used to register and display the provider.
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	// Complete performs a single (non-streaming) completion.
	Complete(context.Context, *CompleteRequest) (*CompleteResponse, error)
	// CompleteStream performs a completion, streaming incremental token deltas. The final
	// chunk has done=true and may carry usage totals.
	CompleteStream(*CompleteRequest, grpc.ServerStreamingServer[CompleteChunk]) error
	mustEmbedUnimplementedModelProviderServer()
}

// UnimplementedModelProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelProviderServer struct{}

func (UnimplementedModelProviderServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedModelProviderServer) Complete(context.Context, *CompleteRequest) (*CompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedModelProviderServer) CompleteStream(*CompleteRequest, grpc.ServerStreamingServer[CompleteChunk]) error {
	return status.Error(codes.Unimplemented, "method CompleteStream not implemented")
}
func (UnimplementedModelProviderServer) mustEmbedUnimplementedModelProviderServer() {}
func (UnimplementedModelProviderServer) testEmbeddedByValue()                       {}

// UnsafeModelProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelProviderServer will
// result in compilation errors.
type UnsafeModelProviderServer interface {
	mustEmbedUnimplementedModelProviderServer()
}

func RegisterModelProviderServer(s grpc.ServiceRegistrar, srv ModelProviderServer) {
	// If the following call panics, it indicates UnimplementedModelProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelProvider_ServiceDesc, srv)
}

func _ModelProvider_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProviderServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProvider_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProviderServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelProvider_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProviderServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProvider_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProviderServer).Complete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelProvider_CompleteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CompleteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModelProviderServer).CompleteStream(m, &grpc.GenericServerStream[CompleteRequest, CompleteChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelProvider_CompleteStreamServer = grpc.ServerStreamingServer[CompleteChunk]

// ModelProvider_ServiceDesc is the grpc.ServiceDesc for ModelProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "torsor.plugin.v1.ModelProvider",
	HandlerType: (*ModelProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _ModelProvider_Info_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _ModelProvider_Complete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CompleteStream",
			Handler:       _ModelProvider_CompleteStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/plugin/proto/model.proto",
}
