// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: internal/plugin/proto/runtime.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkspaceRuntime_Info_FullMethodName              = "/torsor.plugin.v1.WorkspaceRuntime/Info"
	WorkspaceRuntime_CreateWorkspace_FullMethodName   = "/torsor.plugin.v1.WorkspaceRuntime/CreateWorkspace"
	WorkspaceRuntime_StartWorkspace_FullMethodName    = "/torsor.plugin.v1.WorkspaceRuntime/StartWorkspace"
	WorkspaceRuntime_StopWorkspace_FullMethodName     = "/torsor.plugin.v1.WorkspaceRuntime/StopWorkspace"
	WorkspaceRuntime_DestroyWorkspace_FullMethodName  = "/torsor.plugin.v1.WorkspaceRuntime/DestroyWorkspace"
	WorkspaceRuntime_StatusWorkspace_FullMethodName   = "/torsor.plugin.v1.WorkspaceRuntime/StatusWorkspace"
	WorkspaceRuntime_Exec_FullMethodName              = "/torsor.plugin.v1.WorkspaceRuntime/Exec"
	WorkspaceRuntime_ListFiles_FullMethodName         = "/torsor.plugin.v1.WorkspaceRuntime/ListFiles"
	WorkspaceRuntime_ReadFile_FullMethodName          = "/torsor.plugin.v1.WorkspaceRuntime/ReadFile"
	WorkspaceRuntime_WriteFile_FullMethodName         = "/torsor.plugin.v1.WorkspaceRuntime/WriteFile"
	WorkspaceRuntime_SnapshotWorkspace_FullMethodName = "/torsor.plugin.v1.WorkspaceRuntime/SnapshotWorkspace"
	WorkspaceRuntime_RestoreWorkspace_FullMethodName  = "/torsor.plugin.v1.WorkspaceRuntime/RestoreWorkspace"
	WorkspaceRuntime_ForkWorkspace_FullMethodName     = "/torsor.plugin.v1.WorkspaceRuntime/ForkWorkspace"
)

// WorkspaceRuntimeClient is the client API for WorkspaceRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkspaceRuntime is the Torsor backend capability that owns per-user cloud
// workspaces: an isolated, persistent environment (a container today; Firecracker or
// Kubernetes later) where a project's files live and its commands run. It is the
// foundation of the "code actually runs" experience — real file ops, a real PTY/exec,
// and a dev server the gateway can proxy back as a live preview.
//
// Like ModelProvider, runtimes are out-of-process plugins spoken to over gRPC via
// hashicorp/go-plugin, so the kernel stays small and a crashing runtime can't take the
// control plane down. The contract is deliberately runtime-agnostic.
type WorkspaceRuntimeClient interface {
	// Info returns static metadata used to register and display the runtime.
	Info(ctx context.Context, in *RuntimeInfoRequest, opts ...grpc.CallOption) (*RuntimeInfoResponse, error)
	// Lifecycle: create provisions a workspace (e.g. a container + volume) from a spec;
	// start/stop toggle it; destroy removes it and its resources; status reports state.
	CreateWorkspace(ctx context.Context, in *CreateWorkspaceRequest, opts ...grpc.CallOption) (*WorkspaceStatusResponse, error)
	StartWorkspace(ctx context.Context, in *WorkspaceRef, opts ...grpc.CallOption) (*WorkspaceStatusResponse, error)
	StopWorkspace(ctx context.Context, in *StopWorkspaceRequest, opts ...grpc.CallOption) (*WorkspaceStatusResponse, error)
	DestroyWorkspace(ctx context.Context, in *WorkspaceRef, opts ...grpc.CallOption) (*WorkspaceStatusResponse, error)
	StatusWorkspace(ctx context.Context, in *WorkspaceRef, opts ...grpc.CallOption) (*WorkspaceStatusResponse, error)
	// Exec runs a command inside the workspace, streaming stdout/stderr; the final chunk
	// has done=true and carries the exit code. This is the seam terminals are built on.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecChunk], error)
	// File ops operate on the workspace's filesystem (the source of truth once a workspace
	// is live), distinct from the DB-backed project_files snapshot.
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	ReadFile(ctx context.Context, in *FileRef, opts ...grpc.CallOption) (*ReadFileResponse, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	// SnapshotWorkspace captures the workspace's current state (filesystem, and for VM
	// runtimes its memory) as a restorable point, returning a runtime-native snapshot id.
	SnapshotWorkspace(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	// RestoreWorkspace resets a workspace in place back to a previously taken snapshot.
	RestoreWorkspace(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*WorkspaceStatusResponse, error)
	// ForkWorkspace provisions a new workspace from a source workspace/snapshot so an agent
	// can branch without disturbing the original. new_workspace_id is caller-assigned.
	ForkWorkspace(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*WorkspaceStatusResponse, error)
}

type workspaceRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspaceRuntimeClient(cc grpc.ClientConnInterface) WorkspaceRuntimeClient {
	return &workspaceRuntimeClient{cc}
}

func (c *workspaceRuntimeClient) Info(ctx context.Context, in *RuntimeInfoRequest, opts ...grpc.CallOption) (*RuntimeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeInfoResponse)
	err := c.cc.Invoke(ctx, WorkspaceRuntime_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceRuntimeClient) CreateWorkspace(ctx context.Context, in *CreateWorkspaceRequest, opts ...grpc.CallOption) (*WorkspaceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspaceStatusResponse)
	err := c.cc.Invoke(ctx, WorkspaceRuntime_CreateWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceRuntimeClient) StartWorkspace(ctx context.Context, in *WorkspaceRef, opts ...grpc.CallOption) (*WorkspaceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspaceStatusResponse)
	err := c.cc.Invoke(ctx, WorkspaceRuntime_StartWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceRuntimeClient) StopWorkspace(ctx context.Context, in *StopWorkspaceRequest, opts ...grpc.CallOption) (*WorkspaceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspaceStatusResponse)
	err := c.cc.Invoke(ctx, WorkspaceRuntime_StopWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceRuntimeClient) DestroyWorkspace(ctx context.Context, in *WorkspaceRef, opts ...grpc.CallOption) (*WorkspaceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspaceStatusResponse)
	err := c.cc.Invoke(ctx, WorkspaceRuntime_DestroyWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceRuntimeClient) StatusWorkspace(ctx context.Context, in *WorkspaceRef, opts ...grpc.CallOption) (*WorkspaceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspaceStatusResponse)
	err := c.cc.Invoke(ctx, WorkspaceRuntime_StatusWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceRuntimeClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkspaceRuntime_ServiceDesc.Streams[0], WorkspaceRuntime_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceRuntime_ExecClient = grpc.ServerStreamingClient[ExecChunk]

func (c *workspaceRuntimeClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, WorkspaceRuntime_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceRuntimeClient) ReadFile(ctx context.Context, in *FileRef, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, WorkspaceRuntime_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceRuntimeClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, WorkspaceRuntime_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceRuntimeClient) SnapshotWorkspace(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, WorkspaceRuntime_SnapshotWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceRuntimeClient) RestoreWorkspace(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*WorkspaceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspaceStatusResponse)
	err := c.cc.Invoke(ctx, WorkspaceRuntime_RestoreWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceRuntimeClient) ForkWorkspace(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*WorkspaceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspaceStatusResponse)
	err := c.cc.Invoke(ctx, WorkspaceRuntime_ForkWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkspaceRuntimeServer is the server API for WorkspaceRuntime service.
// All implementations must embed UnimplementedWorkspaceRuntimeServer
// for forward compatibility.
//
// WorkspaceRuntime is the Torsor backend capability that owns per-user cloud
// workspaces: an isolated, persistent environment (a container today; Firecracker or
// Kubernetes later) where a project's files live and its commands run. It is the
// foundation of the "code actually runs" experience — real file ops, a real PTY/exec,
// and a dev server the gateway can proxy back as a live preview.
//
// Like ModelProvider, runtimes are out-of-process plugins spoken to over gRPC via
// hashicorp/go-plugin, so the kernel stays small and a crashing runtime can't take the
// control plane down. The contract is deliberately runtime-agnostic.
type WorkspaceRuntimeServer interface {
	// Info returns static metadata used to register and display the runtime.
	Info(context.Context, *RuntimeInfoRequest) (*RuntimeInfoResponse, error)
	// Lifecycle: create provisions a workspace (e.g. a container + volume) from a spec;
	// start/stop toggle it; destroy removes it and its resources; status reports state.
	CreateWorkspace(context.Context, *CreateWorkspaceRequest) (*WorkspaceStatusResponse, error)
	StartWorkspace(context.Context, *WorkspaceRef) (*WorkspaceStatusResponse, error)
	StopWorkspace(context.Context, *StopWorkspaceRequest) (*WorkspaceStatusResponse, error)
	DestroyWorkspace(context.Context, *WorkspaceRef) (*WorkspaceStatusResponse, error)
	StatusWorkspace(context.Context, *WorkspaceRef) (*WorkspaceStatusResponse, error)
	// Exec runs a command inside the workspace, streaming stdout/stderr; the final chunk
	// has done=true and carries the exit code. This is the seam terminals are built on.
	Exec(*ExecRequest, grpc.ServerStreamingServer[ExecChunk]) error
	// File ops operate on the workspace's filesystem (the source of truth once a workspace
	// is live), distinct from the DB-backed project_files snapshot.
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	ReadFile(context.Context, *FileRef) (*ReadFileResponse, error)
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	// SnapshotWorkspace captures the workspace's current state (filesystem, and for VM
	// runtimes its memory) as a restorable point, returning a runtime-native snapshot id.
	SnapshotWorkspace(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	// RestoreWorkspace resets a workspace in place back to a previously taken snapshot.
	RestoreWorkspace(context.Context, *RestoreRequest) (*WorkspaceStatusResponse, error)
	// ForkWorkspace provisions a new workspace from a source workspace/snapshot so an agent
	// can branch without disturbing the original. new_workspace_id is caller-assigned.
	ForkWorkspace(context.Context, *ForkRequest) (*WorkspaceStatusResponse, error)
	mustEmbedUnimplementedWorkspaceRuntimeServer()
}

// UnimplementedWorkspaceRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkspaceRuntimeServer struct{}

func (UnimplementedWorkspaceRuntimeServer) Info(context.Context, *RuntimeInfoRequest) (*RuntimeInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedWorkspaceRuntimeServer) CreateWorkspace(context.Context, *CreateWorkspaceRequest) (*WorkspaceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkspace not implemented")
}
func (UnimplementedWorkspaceRuntimeServer) StartWorkspace(context.Context, *WorkspaceRef) (*WorkspaceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWorkspace not implemented")
}
func (UnimplementedWorkspaceRuntimeServer) StopWorkspace(context.Context, *StopWorkspaceRequest) (*WorkspaceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopWorkspace not implemented")
}
func (UnimplementedWorkspaceRuntimeServer) DestroyWorkspace(context.Context, *WorkspaceRef) (*WorkspaceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyWorkspace not implemented")
}
func (UnimplementedWorkspaceRuntimeServer) StatusWorkspace(context.Context, *WorkspaceRef) (*WorkspaceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StatusWorkspace not implemented")
}
func (UnimplementedWorkspaceRuntimeServer) Exec(*ExecRequest, grpc.ServerStreamingServer[ExecChunk]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedWorkspaceRuntimeServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedWorkspaceRuntimeServer) ReadFile(context.Context, *FileRef) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedWorkspaceRuntimeServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedWorkspaceRuntimeServer) SnapshotWorkspace(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotWorkspace not implemented")
}
func (UnimplementedWorkspaceRuntimeServer) RestoreWorkspace(context.Context, *RestoreRequest) (*WorkspaceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreWorkspace not implemented")
}
func (UnimplementedWorkspaceRuntimeServer) ForkWorkspace(context.Context, *ForkRequest) (*WorkspaceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForkWorkspace not implemented")
}
func (UnimplementedWorkspaceRuntimeServer) mustEmbedUnimplementedWorkspaceRuntimeServer() {}
func (UnimplementedWorkspaceRuntimeServer) testEmbeddedByValue()                          {}

// UnsafeWorkspaceRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkspaceRuntimeServer will
// result in compilation errors.
type UnsafeWorkspaceRuntimeServer interface {
	mustEmbedUnimplementedWorkspaceRuntimeServer()
}

func RegisterWorkspaceRuntimeServer(s grpc.ServiceRegistrar, srv WorkspaceRuntimeServer) {
	// If the following call panics, it indicates UnimplementedWorkspaceRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkspaceRuntime_ServiceDesc, srv)
}

func _WorkspaceRuntime_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuntimeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRuntimeServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRuntime_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRuntimeServer).Info(ctx, req.(*RuntimeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceRuntime_CreateWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRuntimeServer).CreateWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRuntime_CreateWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRuntimeServer).CreateWorkspace(ctx, req.(*CreateWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceRuntime_StartWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRuntimeServer).StartWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRuntime_StartWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRuntimeServer).StartWorkspace(ctx, req.(*WorkspaceRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceRuntime_StopWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRuntimeServer).StopWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRuntime_StopWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRuntimeServer).StopWorkspace(ctx, req.(*StopWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceRuntime_DestroyWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRuntimeServer).DestroyWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRuntime_DestroyWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRuntimeServer).DestroyWorkspace(ctx, req.(*WorkspaceRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceRuntime_StatusWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRuntimeServer).StatusWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRuntime_StatusWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRuntimeServer).StatusWorkspace(ctx, req.(*WorkspaceRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceRuntime_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkspaceRuntimeServer).Exec(m, &grpc.GenericServerStream[ExecRequest, ExecChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspaceRuntime_ExecServer = grpc.ServerStreamingServer[ExecChunk]

func _WorkspaceRuntime_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRuntimeServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRuntime_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRuntimeServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceRuntime_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRuntimeServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRuntime_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRuntimeServer).ReadFile(ctx, req.(*FileRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceRuntime_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRuntimeServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRuntime_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRuntimeServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceRuntime_SnapshotWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRuntimeServer).SnapshotWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRuntime_SnapshotWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRuntimeServer).SnapshotWorkspace(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceRuntime_RestoreWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRuntimeServer).RestoreWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRuntime_RestoreWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRuntimeServer).RestoreWorkspace(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceRuntime_ForkWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceRuntimeServer).ForkWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceRuntime_ForkWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceRuntimeServer).ForkWorkspace(ctx, req.(*ForkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkspaceRuntime_ServiceDesc is the grpc.ServiceDesc for WorkspaceRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkspaceRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "torsor.plugin.v1.WorkspaceRuntime",
	HandlerType: (*WorkspaceRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _WorkspaceRuntime_Info_Handler,
		},
		{
			MethodName: "CreateWorkspace",
			Handler:    _WorkspaceRuntime_CreateWorkspace_Handler,
		},
		{
			MethodName: "StartWorkspace",
			Handler:    _WorkspaceRuntime_StartWorkspace_Handler,
		},
		{
			MethodName: "StopWorkspace",
			Handler:    _WorkspaceRuntime_StopWorkspace_Handler,
		},
		{
			MethodName: "DestroyWorkspace",
			Handler:    _WorkspaceRuntime_DestroyWorkspace_Handler,
		},
		{
			MethodName: "StatusWorkspace",
			Handler:    _WorkspaceRuntime_StatusWorkspace_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _WorkspaceRuntime_ListFiles_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _WorkspaceRuntime_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _WorkspaceRuntime_WriteFile_Handler,
		},
		{
			MethodName: "SnapshotWorkspace",
			Handler:    _WorkspaceRuntime_SnapshotWorkspace_Handler,
		},
		{
			MethodName: "RestoreWorkspace",
			Handler:    _WorkspaceRuntime_RestoreWorkspace_Handler,
		},
		{
			MethodName: "ForkWorkspace",
			Handler:    _WorkspaceRuntime_ForkWorkspace_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _WorkspaceRuntime_Exec_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/plugin/proto/runtime.proto",
}
