// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/plugin/proto/runtime.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfoRequest) Reset() {
	*x = RuntimeInfoRequest{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfoRequest) ProtoMessage() {}

func (x *RuntimeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfoRequest.ProtoReflect.Descriptor instead.
func (*RuntimeInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{0}
}

type RuntimeInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // stable id, e.g. "docker", "mock"
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // human label, e.g. "Docker (local)"
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"` // capability kind, always "workspace_runtime" here
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfoResponse) Reset() {
	*x = RuntimeInfoResponse{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfoResponse) ProtoMessage() {}

func (x *RuntimeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfoResponse.ProtoReflect.Descriptor instead.
func (*RuntimeInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuntimeInfoResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RuntimeInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RuntimeInfoResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// WorkspaceRef identifies an existing workspace.
type WorkspaceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceRef) Reset() {
	*x = WorkspaceRef{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceRef) ProtoMessage() {}

func (x *WorkspaceRef) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceRef.ProtoReflect.Descriptor instead.
func (*WorkspaceRef) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *WorkspaceRef) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type CreateWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`                                        // caller-assigned stable id (e.g. the project id)
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`                                                                       // base image / devcontainer reference
	WorkingDir    string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`                                           // default working directory inside the workspace
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // environment variables
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkspaceRequest) Reset() {
	*x = CreateWorkspaceRequest{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceRequest) ProtoMessage() {}

func (x *CreateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type StopWorkspaceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId    string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // grace period before force-stop
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StopWorkspaceRequest) Reset() {
	*x = StopWorkspaceRequest{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkspaceRequest) ProtoMessage() {}

func (x *StopWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*StopWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *StopWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *StopWorkspaceRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// WorkspaceStatusResponse is the common lifecycle reply.
type WorkspaceStatusResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ContainerId string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"` // runtime-native handle (container id, vm id, ...)
	Status      string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                              // created | running | stopped | destroyed | unknown
	Message     string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                            // optional human-readable detail
	// Where the workspace's app is reachable for live preview, when it exposes one (e.g. a
	// published container port). Empty host/0 port means "no preview available". The
	// control-plane reverse-proxies to preview_host:preview_port.
	PreviewHost   string `protobuf:"bytes,5,opt,name=preview_host,json=previewHost,proto3" json:"preview_host,omitempty"`
	PreviewPort   int32  `protobuf:"varint,6,opt,name=preview_port,json=previewPort,proto3" json:"preview_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceStatusResponse) Reset() {
	*x = WorkspaceStatusResponse{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceStatusResponse) ProtoMessage() {}

func (x *WorkspaceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceStatusResponse.ProtoReflect.Descriptor instead.
func (*WorkspaceStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *WorkspaceStatusResponse) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *WorkspaceStatusResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *WorkspaceStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkspaceStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkspaceStatusResponse) GetPreviewHost() string {
	if x != nil {
		return x.PreviewHost
	}
	return ""
}

func (x *WorkspaceStatusResponse) GetPreviewPort() int32 {
	if x != nil {
		return x.PreviewPort
	}
	return 0
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"` // argv; e.g. ["npm", "run", "dev"]
	WorkingDir    string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *ExecRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ExecRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

type ExecChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // meaningful when done=true
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecChunk) Reset() {
	*x = ExecChunk{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecChunk) ProtoMessage() {}

func (x *ExecChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecChunk.ProtoReflect.Descriptor instead.
func (*ExecChunk) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *ExecChunk) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecChunk) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecChunk) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

// ExecInteractiveRequest is one client->server frame of an interactive session. The first
// frame MUST carry `start`; subsequent frames carry `stdin` bytes or a `resize` event.
type ExecInteractiveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecInteractiveRequest_Start
	//	*ExecInteractiveRequest_Stdin
	//	*ExecInteractiveRequest_Resize
	Payload       isExecInteractiveRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecInteractiveRequest) Reset() {
	*x = ExecInteractiveRequest{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecInteractiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecInteractiveRequest) ProtoMessage() {}

func (x *ExecInteractiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecInteractiveRequest.ProtoReflect.Descriptor instead.
func (*ExecInteractiveRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *ExecInteractiveRequest) GetPayload() isExecInteractiveRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecInteractiveRequest) GetStart() *ExecStart {
	if x != nil {
		if x, ok := x.Payload.(*ExecInteractiveRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecInteractiveRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecInteractiveRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecInteractiveRequest) GetResize() *WinSize {
	if x != nil {
		if x, ok := x.Payload.(*ExecInteractiveRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isExecInteractiveRequest_Payload interface {
	isExecInteractiveRequest_Payload()
}

type ExecInteractiveRequest_Start struct {
	Start *ExecStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"` // required first frame: the command + initial terminal size
}

type ExecInteractiveRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"` // raw bytes to write to the process's stdin
}

type ExecInteractiveRequest_Resize struct {
	Resize *WinSize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"` // terminal was resized to these dimensions
}

func (*ExecInteractiveRequest_Start) isExecInteractiveRequest_Payload() {}

func (*ExecInteractiveRequest_Stdin) isExecInteractiveRequest_Payload() {}

func (*ExecInteractiveRequest_Resize) isExecInteractiveRequest_Payload() {}

type ExecStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"` // argv; empty => the runtime's default shell
	WorkingDir    string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Size          *WinSize               `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"` // initial terminal size (0/0 => runtime default)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStart) Reset() {
	*x = ExecStart{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStart) ProtoMessage() {}

func (x *ExecStart) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStart.ProtoReflect.Descriptor instead.
func (*ExecStart) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *ExecStart) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ExecStart) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecStart) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecStart) GetSize() *WinSize {
	if x != nil {
		return x.Size
	}
	return nil
}

// WinSize is a terminal window size in character cells.
type WinSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WinSize) Reset() {
	*x = WinSize{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WinSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinSize) ProtoMessage() {}

func (x *WinSize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinSize.ProtoReflect.Descriptor instead.
func (*WinSize) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *WinSize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *WinSize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // directory to list (default: working dir)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *ListFilesRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	IsDir         bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{13}
}

func (x *ListFilesResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FileRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRef) Reset() {
	*x = FileRef{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRef) ProtoMessage() {}

func (x *FileRef) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRef.ProtoReflect.Descriptor instead.
func (*FileRef) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *FileRef) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *FileRef) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{15}
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreateDirs    bool                   `protobuf:"varint,4,opt,name=create_dirs,json=createDirs,proto3" json:"create_dirs,omitempty"` // mkdir -p the parent directories
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{16}
}

func (x *WriteFileRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WriteFileRequest) GetCreateDirs() bool {
	if x != nil {
		return x.CreateDirs
	}
	return false
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{17}
}

func (x *WriteFileResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // optional human label for the snapshot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{18}
}

func (x *SnapshotRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SnapshotRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"` // runtime-native handle to pass to Restore/Fork
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                         // optional human-readable detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{19}
}

func (x *SnapshotResponse) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SnapshotResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{20}
}

func (x *RestoreRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *RestoreRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type ForkRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SourceWorkspaceId string                 `protobuf:"bytes,1,opt,name=source_workspace_id,json=sourceWorkspaceId,proto3" json:"source_workspace_id,omitempty"`
	SnapshotId        string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`               // optional; empty = fork from the live state
	NewWorkspaceId    string                 `protobuf:"bytes,3,opt,name=new_workspace_id,json=newWorkspaceId,proto3" json:"new_workspace_id,omitempty"` // caller-assigned id for the forked workspace
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ForkRequest) Reset() {
	*x = ForkRequest{}
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkRequest) ProtoMessage() {}

func (x *ForkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_runtime_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkRequest.ProtoReflect.Descriptor instead.
func (*ForkRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_runtime_proto_rawDescGZIP(), []int{21}
}

func (x *ForkRequest) GetSourceWorkspaceId() string {
	if x != nil {
		return x.SourceWorkspaceId
	}
	return ""
}

func (x *ForkRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *ForkRequest) GetNewWorkspaceId() string {
	if x != nil {
		return x.NewWorkspaceId
	}
	return ""
}

var File_internal_plugin_proto_runtime_proto protoreflect.FileDescriptor

const file_internal_plugin_proto_runtime_proto_rawDesc = "" +
	"\n" +
	"#internal/plugin/proto/runtime.proto\x12\x10torsor.plugin.v1\"\x14\n" +
	"\x12RuntimeInfoRequest\"z\n" +
	"\x13RuntimeInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\"1\n" +
	"\fWorkspaceRef\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"\xef\x01\n" +
	"\x16CreateWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12C\n" +
	"\x03env\x18\x04 \x03(\v21.torsor.plugin.v1.CreateWorkspaceRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"b\n" +
	"\x14StopWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\"\xd7\x01\n" +
	"\x17WorkspaceStatusResponse\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12!\n" +
	"\fpreview_host\x18\x05 \x01(\tR\vpreviewHost\x12!\n" +
	"\fpreview_port\x18\x06 \x01(\x05R\vpreviewPort\"k\n" +
	"\vExecRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\"l\n" +
	"\tExecChunk\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\"\xa5\x01\n" +
	"\x16ExecInteractiveRequest\x123\n" +
	"\x05start\x18\x01 \x01(\v2\x1b.torsor.plugin.v1.ExecStartH\x00R\x05start\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x123\n" +
	"\x06resize\x18\x03 \x01(\v2\x19.torsor.plugin.v1.WinSizeH\x00R\x06resizeB\t\n" +
	"\apayload\"\x98\x01\n" +
	"\tExecStart\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12-\n" +
	"\x04size\x18\x04 \x01(\v2\x19.torsor.plugin.v1.WinSizeR\x04size\"1\n" +
	"\aWinSize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\"I\n" +
	"\x10ListFilesRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"^\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"J\n" +
	"\x11ListFilesResponse\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.torsor.plugin.v1.FileEntryR\aentries\"@\n" +
	"\aFileRef\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\",\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"\x84\x01\n" +
	"\x10WriteFileRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x1f\n" +
	"\vcreate_dirs\x18\x04 \x01(\bR\n" +
	"createDirs\"#\n" +
	"\x11WriteFileResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"J\n" +
	"\x0fSnapshotRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"p\n" +
	"\x10SnapshotResponse\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"T\n" +
	"\x0eRestoreRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\"\x88\x01\n" +
	"\vForkRequest\x12.\n" +
	"\x13source_workspace_id\x18\x01 \x01(\tR\x11sourceWorkspaceId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\x12(\n" +
	"\x10new_workspace_id\x18\x03 \x01(\tR\x0enewWorkspaceId2\x80\n" +
	"\n" +
	"\x10WorkspaceRuntime\x12S\n" +
	"\x04Info\x12$.torsor.plugin.v1.RuntimeInfoRequest\x1a%.torsor.plugin.v1.RuntimeInfoResponse\x12f\n" +
	"\x0fCreateWorkspace\x12(.torsor.plugin.v1.CreateWorkspaceRequest\x1a).torsor.plugin.v1.WorkspaceStatusResponse\x12[\n" +
	"\x0eStartWorkspace\x12\x1e.torsor.plugin.v1.WorkspaceRef\x1a).torsor.plugin.v1.WorkspaceStatusResponse\x12b\n" +
	"\rStopWorkspace\x12&.torsor.plugin.v1.StopWorkspaceRequest\x1a).torsor.plugin.v1.WorkspaceStatusResponse\x12]\n" +
	"\x10DestroyWorkspace\x12\x1e.torsor.plugin.v1.WorkspaceRef\x1a).torsor.plugin.v1.WorkspaceStatusResponse\x12\\\n" +
	"\x0fStatusWorkspace\x12\x1e.torsor.plugin.v1.WorkspaceRef\x1a).torsor.plugin.v1.WorkspaceStatusResponse\x12D\n" +
	"\x04Exec\x12\x1d.torsor.plugin.v1.ExecRequest\x1a\x1b.torsor.plugin.v1.ExecChunk0\x01\x12\\\n" +
	"\x0fExecInteractive\x12(.torsor.plugin.v1.ExecInteractiveRequest\x1a\x1b.torsor.plugin.v1.ExecChunk(\x010\x01\x12T\n" +
	"\tListFiles\x12\".torsor.plugin.v1.ListFilesRequest\x1a#.torsor.plugin.v1.ListFilesResponse\x12I\n" +
	"\bReadFile\x12\x19.torsor.plugin.v1.FileRef\x1a\".torsor.plugin.v1.ReadFileResponse\x12T\n" +
	"\tWriteFile\x12\".torsor.plugin.v1.WriteFileRequest\x1a#.torsor.plugin.v1.WriteFileResponse\x12Z\n" +
	"\x11SnapshotWorkspace\x12!.torsor.plugin.v1.SnapshotRequest\x1a\".torsor.plugin.v1.SnapshotResponse\x12_\n" +
	"\x10RestoreWorkspace\x12 .torsor.plugin.v1.RestoreRequest\x1a).torsor.plugin.v1.WorkspaceStatusResponse\x12Y\n" +
	"\rForkWorkspace\x12\x1d.torsor.plugin.v1.ForkRequest\x1a).torsor.plugin.v1.WorkspaceStatusResponseBGZEgithub.com/magnetoid/torsor/control-plane/internal/plugin/proto;protob\x06proto3"

var (
	file_internal_plugin_proto_runtime_proto_rawDescOnce sync.Once
	file_internal_plugin_proto_runtime_proto_rawDescData []byte
)

func file_internal_plugin_proto_runtime_proto_rawDescGZIP() []byte {
	file_internal_plugin_proto_runtime_proto_rawDescOnce.Do(func() {
		file_internal_plugin_proto_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_plugin_proto_runtime_proto_rawDesc), len(file_internal_plugin_proto_runtime_proto_rawDesc)))
	})
	return file_internal_plugin_proto_runtime_proto_rawDescData
}

var file_internal_plugin_proto_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_internal_plugin_proto_runtime_proto_goTypes = []any{
	(*RuntimeInfoRequest)(nil),      // 0: torsor.plugin.v1.RuntimeInfoRequest
	(*RuntimeInfoResponse)(nil),     // 1: torsor.plugin.v1.RuntimeInfoResponse
	(*WorkspaceRef)(nil),            // 2: torsor.plugin.v1.WorkspaceRef
	(*CreateWorkspaceRequest)(nil),  // 3: torsor.plugin.v1.CreateWorkspaceRequest
	(*StopWorkspaceRequest)(nil),    // 4: torsor.plugin.v1.StopWorkspaceRequest
	(*WorkspaceStatusResponse)(nil), // 5: torsor.plugin.v1.WorkspaceStatusResponse
	(*ExecRequest)(nil),             // 6: torsor.plugin.v1.ExecRequest
	(*ExecChunk)(nil),               // 7: torsor.plugin.v1.ExecChunk
	(*ExecInteractiveRequest)(nil),  // 8: torsor.plugin.v1.ExecInteractiveRequest
	(*ExecStart)(nil),               // 9: torsor.plugin.v1.ExecStart
	(*WinSize)(nil),                 // 10: torsor.plugin.v1.WinSize
	(*ListFilesRequest)(nil),        // 11: torsor.plugin.v1.ListFilesRequest
	(*FileEntry)(nil),               // 12: torsor.plugin.v1.FileEntry
	(*ListFilesResponse)(nil),       // 13: torsor.plugin.v1.ListFilesResponse
	(*FileRef)(nil),                 // 14: torsor.plugin.v1.FileRef
	(*ReadFileResponse)(nil),        // 15: torsor.plugin.v1.ReadFileResponse
	(*WriteFileRequest)(nil),        // 16: torsor.plugin.v1.WriteFileRequest
	(*WriteFileResponse)(nil),       // 17: torsor.plugin.v1.WriteFileResponse
	(*SnapshotRequest)(nil),         // 18: torsor.plugin.v1.SnapshotRequest
	(*SnapshotResponse)(nil),        // 19: torsor.plugin.v1.SnapshotResponse
	(*RestoreRequest)(nil),          // 20: torsor.plugin.v1.RestoreRequest
	(*ForkRequest)(nil),             // 21: torsor.plugin.v1.ForkRequest
	nil,                             // 22: torsor.plugin.v1.CreateWorkspaceRequest.EnvEntry
}
var file_internal_plugin_proto_runtime_proto_depIdxs = []int32{
	22, // 0: torsor.plugin.v1.CreateWorkspaceRequest.env:type_name -> torsor.plugin.v1.CreateWorkspaceRequest.EnvEntry
	9,  // 1: torsor.plugin.v1.ExecInteractiveRequest.start:type_name -> torsor.plugin.v1.ExecStart
	10, // 2: torsor.plugin.v1.ExecInteractiveRequest.resize:type_name -> torsor.plugin.v1.WinSize
	10, // 3: torsor.plugin.v1.ExecStart.size:type_name -> torsor.plugin.v1.WinSize
	12, // 4: torsor.plugin.v1.ListFilesResponse.entries:type_name -> torsor.plugin.v1.FileEntry
	0,  // 5: torsor.plugin.v1.WorkspaceRuntime.Info:input_type -> torsor.plugin.v1.RuntimeInfoRequest
	3,  // 6: torsor.plugin.v1.WorkspaceRuntime.CreateWorkspace:input_type -> torsor.plugin.v1.CreateWorkspaceRequest
	2,  // 7: torsor.plugin.v1.WorkspaceRuntime.StartWorkspace:input_type -> torsor.plugin.v1.WorkspaceRef
	4,  // 8: torsor.plugin.v1.WorkspaceRuntime.StopWorkspace:input_type -> torsor.plugin.v1.StopWorkspaceRequest
	2,  // 9: torsor.plugin.v1.WorkspaceRuntime.DestroyWorkspace:input_type -> torsor.plugin.v1.WorkspaceRef
	2,  // 10: torsor.plugin.v1.WorkspaceRuntime.StatusWorkspace:input_type -> torsor.plugin.v1.WorkspaceRef
	6,  // 11: torsor.plugin.v1.WorkspaceRuntime.Exec:input_type -> torsor.plugin.v1.ExecRequest
	8,  // 12: torsor.plugin.v1.WorkspaceRuntime.ExecInteractive:input_type -> torsor.plugin.v1.ExecInteractiveRequest
	11, // 13: torsor.plugin.v1.WorkspaceRuntime.ListFiles:input_type -> torsor.plugin.v1.ListFilesRequest
	14, // 14: torsor.plugin.v1.WorkspaceRuntime.ReadFile:input_type -> torsor.plugin.v1.FileRef
	16, // 15: torsor.plugin.v1.WorkspaceRuntime.WriteFile:input_type -> torsor.plugin.v1.WriteFileRequest
	18, // 16: torsor.plugin.v1.WorkspaceRuntime.SnapshotWorkspace:input_type -> torsor.plugin.v1.SnapshotRequest
	20, // 17: torsor.plugin.v1.WorkspaceRuntime.RestoreWorkspace:input_type -> torsor.plugin.v1.RestoreRequest
	21, // 18: torsor.plugin.v1.WorkspaceRuntime.ForkWorkspace:input_type -> torsor.plugin.v1.ForkRequest
	1,  // 19: torsor.plugin.v1.WorkspaceRuntime.Info:output_type -> torsor.plugin.v1.RuntimeInfoResponse
	5,  // 20: torsor.plugin.v1.WorkspaceRuntime.CreateWorkspace:output_type -> torsor.plugin.v1.WorkspaceStatusResponse
	5,  // 21: torsor.plugin.v1.WorkspaceRuntime.StartWorkspace:output_type -> torsor.plugin.v1.WorkspaceStatusResponse
	5,  // 22: torsor.plugin.v1.WorkspaceRuntime.StopWorkspace:output_type -> torsor.plugin.v1.WorkspaceStatusResponse
	5,  // 23: torsor.plugin.v1.WorkspaceRuntime.DestroyWorkspace:output_type -> torsor.plugin.v1.WorkspaceStatusResponse
	5,  // 24: torsor.plugin.v1.WorkspaceRuntime.StatusWorkspace:output_type -> torsor.plugin.v1.WorkspaceStatusResponse
	7,  // 25: torsor.plugin.v1.WorkspaceRuntime.Exec:output_type -> torsor.plugin.v1.ExecChunk
	7,  // 26: torsor.plugin.v1.WorkspaceRuntime.ExecInteractive:output_type -> torsor.plugin.v1.ExecChunk
	13, // 27: torsor.plugin.v1.WorkspaceRuntime.ListFiles:output_type -> torsor.plugin.v1.ListFilesResponse
	15, // 28: torsor.plugin.v1.WorkspaceRuntime.ReadFile:output_type -> torsor.plugin.v1.ReadFileResponse
	17, // 29: torsor.plugin.v1.WorkspaceRuntime.WriteFile:output_type -> torsor.plugin.v1.WriteFileResponse
	19, // 30: torsor.plugin.v1.WorkspaceRuntime.SnapshotWorkspace:output_type -> torsor.plugin.v1.SnapshotResponse
	5,  // 31: torsor.plugin.v1.WorkspaceRuntime.RestoreWorkspace:output_type -> torsor.plugin.v1.WorkspaceStatusResponse
	5,  // 32: torsor.plugin.v1.WorkspaceRuntime.ForkWorkspace:output_type -> torsor.plugin.v1.WorkspaceStatusResponse
	19, // [19:33] is the sub-list for method output_type
	5,  // [5:19] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_internal_plugin_proto_runtime_proto_init() }
func file_internal_plugin_proto_runtime_proto_init() {
	if File_internal_plugin_proto_runtime_proto != nil {
		return
	}
	file_internal_plugin_proto_runtime_proto_msgTypes[8].OneofWrappers = []any{
		(*ExecInteractiveRequest_Start)(nil),
		(*ExecInteractiveRequest_Stdin)(nil),
		(*ExecInteractiveRequest_Resize)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_plugin_proto_runtime_proto_rawDesc), len(file_internal_plugin_proto_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_plugin_proto_runtime_proto_goTypes,
		DependencyIndexes: file_internal_plugin_proto_runtime_proto_depIdxs,
		MessageInfos:      file_internal_plugin_proto_runtime_proto_msgTypes,
	}.Build()
	File_internal_plugin_proto_runtime_proto = out.File
	file_internal_plugin_proto_runtime_proto_goTypes = nil
	file_internal_plugin_proto_runtime_proto_depIdxs = nil
}
